Hernández_Fabio.md

Este *pull request* soluciona un error crítico en la página de registro de usuarios, donde no se enviaban los correos electrónicos de confirmación después de completar el proceso de registro.
- Se corrigió la lógica encargada del envío de correos de confirmación.
- Se añadió la invocación correcta al servicio de correo tras la creación del usuario.
- Se verificó y ajustó la configuración SMTP utilizada por la aplicación.
- Se implementaron pruebas unitarias y manuales para asegurar el funcionamiento correcto del flujo de registro con notificación.
- [`Hernández_Fabio.md`](diffhunk://#diff-0a2c6448093a34ccb78660b47ab0980a35ee74b8f192149584a703be59432edbR1-R8):  
Contiene información sobre el estudiante y sus contribuciones al proyecto:
- Nombre completo
- ID institucional
- Referencias a …

:bug: bug: solution bug in register page

---

Escobar_Kevin.md
Pineda_Duglas.md

Este PR incluye:
- Implementación de la vista semanal en el calendario del panel de usuario.
- Corrección de la visualización de eventos recurrentes en la vista mensual.
Closes #11 
Fixes #12

Add weekly calendar view & fix recurring events display

---

Aguilar_Melvin.md

Se ha corregido el formato de perfil de usuarios
Se asegura que los campos no den conflicto con el proyecto

🐛 bug: Solucion para guardar cambios en el perfil de usuario

---

Escobar_Henry.md

Se ha corregido el manejo de campos opcionales en formularios, evitando errores al enviar valores vacíos.  
Se asegura que dichos campos no interrumpan el proceso de guardado si no contienen datos.
Closes #37

:bug: bug: solve optional empty fields forms

---

Gomez_Pamela.md

Esta pull request implementa un modo nocturno adaptable que permite al usuario programar automáticamente el cambio entre los temas claro y oscuro según un horario definido.
- Lógica para activar el modo oscuro según la hora utilizando `useEffect` y `useState`
- Botón en la barra de navegación para activar o desactivar la programación horaria
- Aplicación de clases condicionales con Tailwind (`dark`)
- Almacenamiento de preferencias en `localStorage` para mantenerlas entre sesiones
- Se agrega el archivo `Gomez_Pamela.md` con los datos de la entrega final
- Closes #15
- El usuario puede definir una hora de inicio y fin para activar el modo oscuro automáticamente
- Si no se configura un horario, el modo funciona de forma manual
- Probado en los navegadores Chrome y Firefox

Feat: agregar modo nocturno con programación horaria y archivo de entrega de Pamela Gómez

---

Aguilar_Melvin.md

Se han agregado un campo de búsqueda global
Se ha asegurado que los cambios no generen conflicto

✨ feat: agregando busqueda  global

---

Cabanas_Monica.md

:sparkles: feat: agregar markdown para finalizar taller 3

---

Escobar_Kevin.md
Martinez_Jose.md

En este pull request se arreglo:
Closes #14 
Fixes #13

:sparkles: feat(auth): añadir flujo de autenticación OAuth2 con Google

---

Roque_Cesar.md

🐛 fix: corregir validación en formulario de registro

---

Hernández_Fabio.md

Este *pull request* soluciona un error crítico en la documentación, donde no se había agregado toda la información importante
- Se corrigió la documentación del proyecto
- [`Hernández_Fabio.md`](diffhunk://#diff-0a2c6448093a34ccb78660b47ab0980a35ee74b8f192149584a703be59432edbR1-R8):  
Contiene información sobre el estudiante y sus contribuciones al proyecto:
- Nombre completo
- ID institucional
- Referencias a issues relacionados:
- Issue de funcionalidad: `#44`
- Issue de bug: `#38`
- Issue de discusión: `#38`
Con esta corrección, el sistema ahora envía correctamente los correos de confirmación al registrar un nuevo usuario, mejorando significativamente la experiencia del usuario y asegurando el correcto funcionamiento del sistema de notificaciones.

:bug: fix: solution bug in documentation by project

---

Mena_Rodrigo.md

Se implementó la funcionalidad solicitada.
Closes #63

✨ feat: agregar sección de comentarios al final de post (issue #63)

---

Escobar_Henry.md

Solve login code not beign sent

:bug: fix: help solving issue

---

Francisco_Rosa.md

:sparkles: add: feature and bug issues with my .md

---

Figueroa_Fernando.md

Este Pull Request agrega un nuevo archivo `Figueroa_Fernando.md `con la información del estudiante y referencias a los issues relacionados.
- Se añadió el nombre completo del estudiante: **Fernando José Figueroa Olivo**
- Se incluyó el carné: **00019921**
- Se documentaron los issues relacionados:
- Issue de feature: #69
- Issue de bug corregido: #67
- Discusión comentada: #61
Closes #67

🐛 fix: resolver tasa de IVA aplicada incorrectamente (fix #67)

---

Diaz_David.md

Se ha creado la documentación según lo solicitado

✨ feat: documentación del proyecto

---

Rodolfo_Garcia.md

Se agrego numero de issue en el cual comente. # 36

:bug: agrege el numero del issue en el cual comente :sparkles:

---

Ascencio_Brandon.md

Esta Pull Request implementa la funcionalidad solicitada en el issue #60.
- Se agregaron alertas visuales en la interfaz.
- Las notificaciones se activan 24 horas antes de la fecha límite.
- Se añadió una opción para desactivar notificaciones.
Closes #60

✨ feat: add archivo .md Taller 03

---

Diaz_Melvin.md

Se agrego el archivo Diaz_Melvin.md con los requisitos solicitados para la realizacion del taller 03. Se implementó la validación de formato de correo electrónico en formulario de inicio de sesión.
closes #33

✨ feat(diaz_melvin.md): agregar archivo Diaz_Melvin.md (closes #33)

---

Guerra_Salvador.md

Add Markdown file Salvador Guerra

---

Martinez_kevin.md

**Propósito:**
Este PR soluciona un error donde la paginación de la galería de imágenes no funcionaba correctamente al aplicar filtros. Ahora, los usuarios pueden navegar por todas las páginas de resultados filtrados sin problemas.
**Issue Solucionado:**
Closes #95

🐛 fix: Corrected pagination in gallery with active filters

---

Leiva_Omar.md

Anteriormente, al marcar como completada una instancia de una tarea recurrente, el sistema actualizaba de forma errónea el estado de la tarea padre o plantilla. Esto causaba que todas las futuras instancias de la misma serie también se marcaran incorrectamente como completadas.
Esta corrección modifica la lógica de gestión de tareas para asegurar que cada instancia de una tarea recurrente mantenga su propio estado de completitud de manera independiente. El servicio de actualización de tareas ha sido ajustado para operar únicamente sobre la instancia específica seleccionada, sin impactar otras ocurrencias de la misma serie recurrente.
Con este cambio, los usuarios pueden ahora marcar una ocurrencia particular de una tarea recurrente como finalizada sin que esto afecte el estado de las …

🐛 fix: enable individual completion for recurring task instances (36)

---

Robles_Romero.md

**Descripción del cambio**:  
Se corrigió el manejo de eventos en el componente Button que causaba comportamientos inconsistentes al:
- No emitir el evento `@click` en móviles
- Disparar doble clic accidental en algunos navegadores
- No propagar eventos correctamente en formularios
**Cambios realizados**:  
✅ Reemplazado `v-on:click` por `@click.native` para mejor compatibilidad  
✅ Añadido debounce de 300ms para prevenir doble clic  
✅ Implementado `event.stopPropagation()` para formularios  
**Impacto**:  
- Mejora la experiencia en dispositivos táctiles  
- Elimina falsos positivos en envíos de formularios  
- Mantiene retrocompatibilidad  
**Cómo probar**:  
1. Probar clics en desktop/mobile  
2. Verificar en formularios con submit  
3. Intentar doble clic rápido

🐛 fix: change events of Button

---

Aguilar_Gerardo.md

Este Pull Request resuelve el issue **[#112 - Implementación de formulario de registro de usuarios]**. Se desarrolló la funcionalidad correspondiente al formulario de registro, permitiendo a los usuarios crear una cuenta ingresando sus datos básicos.
---
- Se implementó el formulario de registro con campos para nombre, correo, contraseña y confirmación.
- Se añadieron validaciones básicas en el formulario.
- Se creó la estructura inicial para enviar los datos al backend.
---
Closes #112

✨ feat: formulario de registro de usuarios

---

Robles_Romero.md

Implementación de la funcionalidad para subir documentos PDF al sistema, incluyendo:  
- Componente de carga de archivos  
- Validaciones (tipo PDF, tamaño máximo 10MB)  
- Vista previa del documento  
✅ Nuevo componente `FileUploader.vue`  
✅ Lógica de validación en frontend y backend  
✅ Integración con el storage S3  
✅ Pruebas unitarias con Jest  
1. Navegar a la sección de documentos  
2. Intentar subir diferentes archivos (PDF válidos/no válidos)  
3. Verificar:  
- Mensajes de error claros  
- Límite de tamaño funcionando  
- Vista previa generada correctamente  
- Se actualizó la documentación de la API en `/docs/api`  
- Configuración necesaria en `.env`:

✨ feat: upload PDF module

---

Huezo_Enrique.md

✨ feat: add real-time validation to profile form fields

---

Sanchez_Ronald.md

fix: Corregir boton de guardado en formulario

---

Guzman_Rene.md

Se agregó el campo para registrar el numero de factura en el formulario de la solicitud del credito.
Closes #52

:sparkles: feat: campo NumeroFactura agregado

---

Campos_Denys.md

**Resumen:**
Este PR soluciona un error donde los cambios realizados en la página de perfil de usuario (ej. biografía, nombre) no se persistían correctamente ni reflejaban feedback visual inmediato tras hacer clic en "Guardar cambios". El usuario necesitaba recargar la página para ver los cambios aplicados.
**Causa del error identificada:**
La función `saveProfileChanges` en `profile.js` presentaba un `TypeError` debido a [ *aquí puedes inventar la causa específica, por ejemplo: "una incorrecta serialización de los datos del formulario antes de la petición AJAX" o "un manejo inadecuado de la promesa de la petición fetch, lo que impedía la correcta actualización del estado y el feedback al usuario."* ]. Esto impedía que la petición se enviara correctamente o que la UI se actualizara tras …

:bug: fix: corregir persistencia errónea de imagen de perfil

---

Rivas_Michelle.md

This pull request fixes the issue in the **clients view**, where applied filters—especially the **Branch** filter—were not affecting the displayed results as expected.
- Fixed the construction of the search `payload` to ensure that selected filter values are correctly included.
- Verified that the **Branch** field is retained in state and properly sent to the backend.
- Adjusted the logic before the fetch to prevent filters from being overwritten or reset prior to sending the request.
Closes #145 
Fixes: filter logic issue in the clients view  
Resolves: bug where search results were not reflecting active filters
---
Este pull request soluciona el problema en la **vista de clientes**, donde los filtros aplicados —en especial el de **Sucursal**— no estaban afectando los resultados …

fix: clients view filters not working

---

README.md
ValenciaPeña_LuisMario.md
docs/guia.md

Closes #55
Incluye README, carpeta docs/ y ValenciaPeña_LuisMario.md.

feat(docs): documentación inicial y entrega de práctica

---

Lopez_Ricardo.md

La funcionalidad de verificación en dos pasos ha sido implementada exitosamente, haciendo referencia al issue #124 
---
- Se añadió un paso adicional al login para ingresar un código enviado por correo electrónico.
- Se incorporó una opción en el perfil del usuario para activar o desactivar 2FA.
- Se implementó una vista para ingresar el código de verificación.
- Se añadieron validaciones para impedir el acceso sin el segundo factor.
- Se gestionaron estados de sesión para usuarios con o sin 2FA habilitado.
---
---
Closes #124

✨ feat: add two factor authentication (2FA via email code)

---

Figueroa_Fernando.md

El usuario debería puede seleccionar distintos medios de pago (efectivo, tarjeta, transferencia, etc.)
Closes #69

✨ feat: agregar múltiples métodos de pago

---

Hernández_Carlos.md

Esta implementación completa los requerimientos descritos en el siguiente issue a cerrar: Closes #151

Implementación del panel de administrador

---

Rodriguez_David.md

Este Pull Request implementa la autenticación mediante la cuenta de Google usando OAuth2. Permite a los usuarios iniciar sesión de forma segura y rápida con su cuenta de Google.
- Integración de Google Sign-In en frontend.
- Endpoint en backend para validar token de Google.
- Actualización de la interfaz de login.
Closes #107

feat: Implementar autenticación con Google en el login

---

Martinez_Mario.md

Dentro del presente pull request se encuentran commits abordando las posibles soluciones para todas las problematicas que esten relacionadas con el issue #100 segun la implementacion inadecuada de un segment tree

Merge regarding issue #100 fix/segment tree

---

Zacatales_César.md

Este pull request resuelve el issue #159, donde al hacer clic en el botón **"Actualizar perfil"** no se ejecutaba ninguna acción o se lanzaba un error en consola relacionado con el formulario.
- Corrección en el acceso al valor de los inputs del formulario (`undefined.value`).
- Se agregó validación previa para asegurar que los campos estén definidos antes de acceder a sus propiedades.
- Se mejoró el manejo del evento de envío del formulario para evitar errores silenciosos.
- Se añadió mensaje de éxito o error según la respuesta del backend.
1. Inicia sesión en el sistema.
2. Ve a la sección "Perfil".
3. Modifica cualquier dato (ej. nombre).
4. Haz clic en el botón "Actualizar perfil".
5. Debería procesarse correctamente y mostrarse un mensaje de éxito o error.
Antes:  
`TypeError: Cannot …

🐛 Bugfix: Error al actualizar perfil – Fixes #159
